import type { LocationItem } from '../types';

export const INITIAL_LOCATIONS: LocationItem[] = [
  {
    id: 'loc-dhm',
    division: 'Dhaka',
    district: 'Dhaka',
    upazila: 'Dhamrai (ধামরাই)',
    unions: [
      'Dhamrai Sadar',
      'Amta',
      'Baisakanda',
      'Balia',
      'Bhararia',
      'Chauhat',
      'Gangutia',
      'Jadabpur',
      'Kulla',
      'Kushura',
      'Nannar',
      'Rowail',
      'Sanora',
      'Sombhag',
      'Sutiakhag',
    ],
    isActive: true,
  },
  {
    id: 'loc-svr',
    division: 'Dhaka',
    district: 'Dhaka',
    upazila: 'Savar (সাভার)',
    unions: [
      'Savar Sadar',
      'Aminbazar',
      'Ashulia',
      'Bhakurta',
      'Birulia',
      'Dhamsona',
      'Kaundia',
      'Pathalia',
      'Shimulia',
      'Tetuljhora',
      'Yarpur',
    ],
    isActive: true,
  },
  {
    id: 'loc-mnk-sadar',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Manikganj Sadar (মানিকগঞ্জ সদর)',
    unions: ['Atigram', 'Betila Mitara', 'Bhararia', 'Dighi', 'Garpara', 'Jaagir', 'Nabagram', 'Putail'],
    isActive: true,
  },
  {
    id: 'loc-mnk-singair',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Singair (সিংগাইর)',
    unions: ['Singair Sadar', 'Baldhara', 'Baira', 'Chandhar', 'Charigram', 'Dhalla', 'Jamirta', 'Joymantop', 'Saista', 'Talta'],
    isActive: true,
  },
  {
    id: 'loc-mnk-saturia',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Saturia (সাটুরিয়া)',
    unions: ['Saturia Sadar', 'Baliati', 'Baraid', 'Dargagram', 'Dhanakora', 'Fukurhati', 'Hargaj', 'Tilli'],
    isActive: true,
  },
  {
    id: 'loc-mnk-shivalaya',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Shivalaya (শিবালয়)',
    unions: ['Shivalaya Sadar', 'Aricha', 'Tehota', 'Utholi', 'Shimulia'],
    isActive: true,
  },
  {
    id: 'loc-mnk-harirampur',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Harirampur (হরিরামপুর)',
    unions: ['Harirampur Sadar', 'Balla', 'Chala', 'Gopinathpur', 'Lesranganj', 'Sutaloori'],
    isActive: true,
  },
  {
    id: 'loc-mnk-ghior',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Ghior (ঘিওর)',
    unions: ['Ghior Sadar', 'Baniachong', 'Balia Khora', 'Nali', 'Paira', 'Singjuri'],
    isActive: true,
  },
  {
    id: 'loc-mnk-daulatpur',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Daulatpur (দৌলতপুর)',
    unions: ['Daulatpur Sadar', 'Bachamara', 'Baghutia', 'Chakmirpur', 'Dhamswar', 'Jionpur', 'Khalsi'],
    isActive: true,
  },
];

export const INITIAL_HOSPITALS = [
  { name: 'Dhamrai Upazila Health Complex (ধামরাই উপজেলা স্বাস্থ্য কমপ্লেক্স)', district: 'Dhaka', upazila: 'Dhamrai' },
  { name: 'Enam Medical College & Hospital, Savar (এনাম মেডিকেল কলেজ হাসপাতাল)', district: 'Dhaka', upazila: 'Savar' },
  { name: 'Savar Upazila Health Complex (সাভার উপজেলা স্বাস্থ্য কমপ্লেক্স)', district: 'Dhaka', upazila: 'Savar' },
  { name: 'Manikganj 250 Bed District Hospital (মানিকগঞ্জ ২৫০ শয্যা বিশিষ্ট জেলা হাসপাতাল)', district: 'Manikganj', upazila: 'Manikganj Sadar' },
  { name: 'Colonel Malek Medical College Hospital (কর্নেল মালেক মেডিকেল কলেজ হাসপাতাল)', district: 'Manikganj', upazila: 'Manikganj Sadar' },
  { name: 'Singair Upazila Health Complex (সিংগাইর উপজেলা স্বাস্থ্য কমপ্লেক্স)', district: 'Manikganj', upazila: 'Singair' },
  { name: 'Saturia Upazila Health Complex (সাটুরিয়া উপজেলা স্বাস্থ্য কমপ্লেক্স)', district: 'Manikganj', upazila: 'Saturia' },
  { name: 'Dhaka Medical College Hospital (ডিএমসিএইচ)', district: 'Dhaka', upazila: 'Dhaka' },
];

export const INITIAL_BRANCHES = [
  {
    id: 'br-dhm',
    organizationId: 'org-roktobondon',
    name: 'Dhamrai Chapter',
    nameBn: 'ধামরাই শাখা',
    district: 'Dhaka',
    upazila: 'Dhamrai',
    coordinatorName: 'মো: আরিফুল ইসলাম',
    coordinatorPhone: '+8801712345001',
    isActive: true,
  },
  {
    id: 'br-svr',
    organizationId: 'org-roktobondon',
    name: 'Savar Chapter',
    nameBn: 'সাভার শাখা',
    district: 'Dhaka',
    upazila: 'Savar',
    coordinatorName: 'তানভীর আহমেদ',
    coordinatorPhone: '+8801812345002',
    isActive: true,
  },
  {
    id: 'br-mnk',
    organizationId: 'org-roktobondon',
    name: 'Manikganj Chapter',
    nameBn: 'মানিকগঞ্জ শাখা',
    district: 'Manikganj',
    upazila: 'Manikganj Sadar',
    coordinatorName: 'রাশেদুল হাসান',
    coordinatorPhone: '+8801912345003',
    isActive: true,
  },
];
