import type { LocationItem } from '../types';

export const INITIAL_LOCATIONS: LocationItem[] = [
  {
    id: 'loc-dhm',
    division: 'Dhaka',
    district: 'Dhaka',
    upazila: 'Dhamrai (ধামরাই)',
    unions: [
      'Dhamrai Sadar',
      'Amta',
      'Baisakanda',
      'Balia',
      'Bhararia',
      'Chauhat',
      'Gangutia',
      'Jadabpur',
      'Kulla',
      'Kushura',
      'Nannar',
      'Rowail',
      'Sanora',
      'Sombhag',
      'Sutipara',
    ],
    isActive: true,
  },
  {
    id: 'loc-svr',
    division: 'Dhaka',
    district: 'Dhaka',
    upazila: 'Savar (সাভার)',
    unions: [
      'Savar Sadar',
      'Aminbazar',
      'Ashulia',
      'Bhakurta',
      'Birulia',
      'Dhamsona',
      'Kaundia',
      'Pathalia',
      'Shimulia',
      'Tetuljhora',
      'Yarpur',
    ],
    isActive: true,
  },
  {
    id: 'loc-mnk-sadar',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Manikganj Sadar (মানিকগঞ্জ সদর)',
    unions: ['Atigram', 'Betila Mitara', 'Bhararia', 'Dighi', 'Garpara', 'Jaagir', 'Nabagram', 'Putail'],
    isActive: true,
  },
  {
    id: 'loc-mnk-singair',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Singair (সিংগাইর)',
    unions: ['Singair Sadar', 'Baldhara', 'Baira', 'Chandhar', 'Charigram', 'Dhalla', 'Jamirta', 'Joymantop', 'Saista', 'Talta'],
    isActive: true,
  },
  {
    id: 'loc-mnk-saturia',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Saturia (সাটুরিয়া)',
    unions: ['Saturia Sadar', 'Baliati', 'Baraid', 'Dargagram', 'Dhanakora', 'Fukurhati', 'Hargaj', 'Tilli'],
    isActive: true,
  },
  {
    id: 'loc-mnk-shivalaya',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Shivalaya (শিবালয়)',
    unions: ['Shivalaya Sadar', 'Aricha', 'Tehota', 'Utholi', 'Shimulia'],
    isActive: true,
  },
  {
    id: 'loc-mnk-harirampur',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Harirampur (হরিরামপুর)',
    unions: ['Harirampur Sadar', 'Balla', 'Chala', 'Gopinathpur', 'Lesranganj', 'Sutaloori'],
    isActive: true,
  },
  {
    id: 'loc-mnk-ghior',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Ghior (ঘিওর)',
    unions: ['Ghior Sadar', 'Baniachong', 'Balia Khora', 'Nali', 'Paira', 'Singjuri'],
    isActive: true,
  },
  {
    id: 'loc-mnk-daulatpur',
    division: 'Dhaka',
    district: 'Manikganj',
    upazila: 'Daulatpur (দৌলতপুর)',
    unions: ['Daulatpur Sadar', 'Bachamara', 'Baghutia', 'Chakmirpur', 'Dhamswar', 'Jionpur', 'Khalsi'],
    isActive: true,
  },
  {
    id: 'loc-dhk-city',
    division: 'Dhaka',
    district: 'Dhaka',
    upazila: 'Dhaka City (ঢাকা মহানগর)',
    unions: [
      'Mirpur (মিরপুর)',
      'Dhanmondi (ধানমন্ডি)',
      'Mohammadpur (মোহাম্মদপুর)',
      'Uttara (উত্তরা)',
      'Gulshan (গুলশান)',
      'Banani (বনানী)',
      'Badda (বাড্ডা)',
      'Motijheel (মতিঝিল)',
      'Old Dhaka (পুরান ঢাকা)',
      'Jatrabari (যাত্রাবাড়ী)',
      'Rampura (রামপুরা)',
      'Khilgaon (খিলগাঁও)',
      'Shahbag (শাহবাগ)',
      'Farmgate (ফার্মগেট)',
      'Shyamoli (শ্যামলী)',
    ],
    isActive: true,
  },
  {
    id: 'loc-dhk-keraniganj',
    division: 'Dhaka',
    district: 'Dhaka',
    upazila: 'Keraniganj (কেরানীগঞ্জ)',
    unions: [
      'Zinjira (জিনজিরা)',
      'Kalatia (কলাতিয়া)',
      'Rohitpur (রোহিতপুর)',
      'Basta (বাস্তা)',
      'Subhadya (শুভাঢ্যা)',
      'Taranagar (তারানগর)',
      'Shakharinagar (শাখারীনগর)',
      'Hazratpur (হযরতপুর)',
    ],
    isActive: true,
  },
  {
    id: 'loc-gzp-sadar',
    division: 'Dhaka',
    district: 'Gazipur',
    upazila: 'Gazipur Sadar (গাজীপুর সদর)',
    unions: [
      'Joydebpur (জয়দেবপুর)',
      'Tongi (টঙ্গী)',
      'Konabari (কোনাবাড়ী)',
      'Board Bazar (বোর্ড বাজার)',
      'Salna (সালনা)',
      'Kashimpur (কাশিমপুর)',
      'Basan (বাসন)',
      'Pubail (পুবাইল)',
    ],
    isActive: true,
  },
  {
    id: 'loc-gzp-kaliakair',
    division: 'Dhaka',
    district: 'Gazipur',
    upazila: 'Kaliakair (কালিয়াকৈর)',
    unions: [
      'Kaliakair Sadar',
      'Chandra (চন্দ্রা)',
      'Mouchak (মৌচাক)',
      'Chapair (চাপাইর)',
      'Boali (বোয়ালী)',
      'Fulbaria (ফুলবাড়িয়া)',
      'Sutrapur (সূত্রাপুর)',
      'Sreefaltali (শ্রীফলতলী)',
    ],
    isActive: true,
  },
];

export const INITIAL_HOSPITALS = [
  { name: 'Dhamrai Upazila Health Complex (ধামরাই উপজেলা স্বাস্থ্য কমপ্লেক্স)', district: 'Dhaka', upazila: 'Dhamrai' },
  { name: 'Enam Medical College & Hospital, Savar (এনাম মেডিকেল কলেজ হাসপাতাল)', district: 'Dhaka', upazila: 'Savar' },
  { name: 'Savar Upazila Health Complex (সাভার উপজেলা স্বাস্থ্য কমপ্লেক্স)', district: 'Dhaka', upazila: 'Savar' },
  { name: 'Kalampur General Hospital (কালামপুর জেনারেল হাসপাতাল)', district: 'Dhaka', upazila: 'Dhamrai' },
  { name: 'Manikganj 250 Bed District Hospital (মানিকগঞ্জ ২৫০ শয্যা বিশিষ্ট জেলা হাসপাতাল)', district: 'Manikganj', upazila: 'Manikganj Sadar' },
  { name: 'Colonel Malek Medical College Hospital (কর্নেল মালেক মেডিকেল কলেজ হাসপাতাল)', district: 'Manikganj', upazila: 'Manikganj Sadar' },
  { name: 'Singair Upazila Health Complex (সিংগাইর উপজেলা স্বাস্থ্য কমপ্লেক্স)', district: 'Manikganj', upazila: 'Singair' },
  { name: 'Saturia Upazila Health Complex (সাটুরিয়া উপজেলা স্বাস্থ্য কমপ্লেক্স)', district: 'Manikganj', upazila: 'Saturia' },
  { name: 'Dhaka Medical College Hospital (ডিএমসিএইচ)', district: 'Dhaka', upazila: 'Dhaka City' },
  { name: 'Shaheed Suhrawardy Medical College Hospital', district: 'Dhaka', upazila: 'Dhaka City' },
  { name: 'BSMMU (পিজি হাসপাতাল)', district: 'Dhaka', upazila: 'Dhaka City' },
  { name: 'National Institute of Cardiovascular Diseases (NICVD)', district: 'Dhaka', upazila: 'Dhaka City' },
  { name: 'NITOR (পঙ্গু হাসপাতাল)', district: 'Dhaka', upazila: 'Dhaka City' },
  { name: 'Kurmitola General Hospital', district: 'Dhaka', upazila: 'Dhaka City' },
  { name: 'Shaheed Tajuddin Ahmad Medical College Hospital', district: 'Gazipur', upazila: 'Gazipur Sadar' },
  { name: 'Bangladesh Red Crescent Blood Centre', district: 'Dhaka', upazila: 'Dhaka City' },
  { name: 'Quantum Lab & Blood Bank', district: 'Dhaka', upazila: 'Dhaka City' },
  { name: 'Sandhani Central Blood Bank (DMC)', district: 'Dhaka', upazila: 'Dhaka City' },
];

export const INITIAL_BRANCHES = [
  {
    id: 'br-dhm',
    organizationId: 'org-roktobondon',
    name: 'Dhamrai Chapter',
    nameBn: 'ধামরাই শাখা',
    district: 'Dhaka',
    upazila: 'Dhamrai',
    coordinatorName: 'মো: আরিফুল ইসলাম',
    coordinatorPhone: '+8801712345001',
    isActive: true,
  },
  {
    id: 'br-svr',
    organizationId: 'org-roktobondon',
    name: 'Savar Chapter',
    nameBn: 'সাভার শাখা',
    district: 'Dhaka',
    upazila: 'Savar',
    coordinatorName: 'তানভীর আহমেদ',
    coordinatorPhone: '+8801812345002',
    isActive: true,
  },
  {
    id: 'br-mnk',
    organizationId: 'org-roktobondon',
    name: 'Manikganj Chapter',
    nameBn: 'মানিকগঞ্জ শাখা',
    district: 'Manikganj',
    upazila: 'Manikganj Sadar',
    coordinatorName: 'রাশেদুল হাসান',
    coordinatorPhone: '+8801912345003',
    isActive: true,
  },
];
